### ISSUE TITLE
Intermittent "Missing pending object in plan" error 

### ISSUE THREAD

**Issue by truongnht** [hashicorp/terraform-provider-http#369] opened 2024-01-12 10:39 UTC
### Terraform CLI and Provider Versions

Terraform versions: v1.5.*, v1.6.*
Provider version: >= 3.1.0

### Terraform Configuration

```terraform
locals {
  crds = [
    "crd-alertmanagerconfigs",
    "crd-alertmanagers",
    "crd-podmonitors",
    "crd-probes",
    "crd-prometheusagents",
    "crd-prometheuses",
    "crd-prometheusrules",
    "crd-scrapeconfigs",
    "crd-servicemonitors",
    "crd-thanosrulers"
  ]
}

data "http" "prometheus_crds" {
  for_each = toset(local.crds)
  url      = "https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-${var.chart_version}/charts/kube-prometheus-stack/charts/crds/crds/${each.key}.yaml"

  lifecycle {
    postcondition {
      condition     = self.status_code == 200
      error_message = "Unable to read remote manifest"
    }
  }
}

resource "kubectl_manifest" "crd_provisioner" {
  for_each          = data.http.prometheus_crds
  apply_only        = true
  force_conflicts   = true
  server_side_apply = true
  wait              = true
  yaml_body         = each.value.response_body
}
```

### Expected Behavior

terraform apply should always work

### Actual Behavior

Sometimes we get into the below error during `terraform apply`, rerunning it a few times will fix the issue. 

```shell
│ Error: Missing pending object in plan
│ 
│   on .terraform/modules/k8s_addons/modules/prometheus-crds/main.tf line 16:
│   16: data "http" "prometheus_crds" {
│ 
│ Instance
│ module.k8s_addons.module.prometheus_crds[0].data.http.prometheus_crds["crd-servicemonitors"] is
│ marked as having a change pending but that change is not recorded in the plan. This is a bug in
│ Terraform; please report it.
╵
╷
│ Error: Missing pending object in plan
│ 
│   on .terraform/modules/k8s_addons/modules/prometheus-crds/main.tf line 16:
│   16: data "http" "prometheus_crds" {
│ 
│ Instance
│ module.k8s_addons.module.prometheus_crds[0].data.http.prometheus_crds["crd-servicemonitors"] is
│ marked as having a change pending but that change is not recorded in the plan. This is a bug in
│ Terraform; please report it.
╵
╷
│ Error: Missing pending object in plan
│ 
│   on .terraform/modules/k8s_addons/modules/prometheus-crds/main.tf line 16:
│   16: data "http" "prometheus_crds" {
│ 
│ Instance
│ module.k8s_addons.module.prometheus_crds[0].data.http.prometheus_crds["crd-podmonitors"] is
│ marked as having a change pending but that change is not recorded in the plan. This is a bug in
│ Terraform; please report it.
╵
```

### Steps to Reproduce

1. `terraform apply -auto-approve`

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment] 2024-01-12 16:50
Hi @truongnht 👋 

Sorry you ran into trouble here.

We're unable to reproduce the issue you described, and the error is suggestive of a possible issue within Terraform itself:

> This is a bug in Terraform; please report it.

Looking at the Terraform repository, there does appear to be a similar issue that has been raised - [Instance module.abc.data.aws_lambda_invocation.xyz["123"] is marked as having a change pending but that change is not recorded in the plan.](https://github.com/hashicorp/terraform/issues/34310#top). The most recent [comment](https://github.com/hashicorp/terraform/issues/34310#issuecomment-1863490609) on this issue appears to indicate that the OP is observing the same behaviour with Terraform `v1.5.3`, so you might want to add your findings to that issue.

**Comment by bflad** [comment] 2024-02-29 18:59
Closing as this appears to have been/be an upstream Terraform bug and since there was no response. Please followup upstream if you are still running into trouble.

**Closed by bflad** 2024-02-29 18:59 UTC
Labels: bug

**Comment by fhemberger** [comment] 2024-03-21 12:41
Hmm. Just ran into the same issue.

Terraform 1.7.5
Provider: 3.4.2

No idea why, but removing the lifecycle stanza seems to help:

```hcl
lifecycle {
  postcondition {
    condition     = contains([200, 301, 302], self.status_code)
    error_message = "Status code invalid"
  }
}
```
